version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
    env_file:
      - ./server/.env
  db:
    image: postgres
    networks:
      - webnet
      - pgadminnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    expose:
      - "5432"
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./server/.env
    ports:
      - "54321:80"
    depends_on:
      - db
    logging:
      driver: none
    networks:
      - pgadminnet
  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - webnet
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      FLASK_ENV: development
      FLASK_APP: ./api.py
    volumes:
      - ./server:/telehelp/server
    command: [
        "./wait-for-it.sh",
        "-t",
        "30",
        "db:5432",
        "--",
        "flask",
        "run",
        "--host",
        "0.0.0.0", # Listen on all interfaces
      ]
networks:
  webnet:
  pgadminnet:
    driver: bridge
volumes:
  pgdata:
